/**
    股票日K图数据
    股票 开市
    时间，开盘，收盘，最高，最低，成交量，成交金额，振幅
 */
DROP TABLE STOCK_NEW_VALUE_HISTORY;
SELECT *
FROM STOCK_NEW_VALUE_HISTORY;
CREATE TABLE STOCK_NEW_VALUE_HISTORY (
  STOCK_CODE     VARCHAR2(255),
  STOCK_NAME     VARCHAR2(255),
  STOCK_DATE     VARCHAR2(255),
  OPEN_MARKET    VARCHAR2(255),
  CLOSE_MARKET   VARCHAR2(255),
  MAX_PRICE      VARCHAR2(255),
  MIN_PRICE      VARCHAR2(255),
  VOL            VARCHAR2(255),
  TRADING_VOLUME VARCHAR2(255),
  AMPLITUDE      VARCHAR2(255),
  TYPE_K         VARCHAR2(5)
);
ALTER TABLE STOCK_NEW_VALUE_HISTORY
  ADD (CREATE_TIME DATE DEFAULT SYSDATE);
INSERT INTO STOCK_NEW_VALUE_HISTORY (STOCK_CODE, STOCK_NAME, STOCK_DATE, OPEN_MARKET, CLOSE_MARKET, MAX_PRICE, MIN_PRICE, VOL, TRADING_VOLUME, TYPE_K)
VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10);

/**
  股票分时图数据存储
 */
SELECT *
FROM STOCK_TIME_DIVISION
ORDER BY CREATE_TIME DESC;
CREATE TABLE STOCK_TIME_DIVISION (
  STOCK_CODE  VARCHAR2(255),
  STOCK_NAME  VARCHAR2(255),
  STOCK_DATE  VARCHAR2(255),
  NET_VALUE   VARCHAR2(255),
  VOL         VARCHAR2(255),
  NET_VALUE_2 VARCHAR2(255),
  TEMP        VARCHAR2(1)
);
ALTER TABLE STOCK_TIME_DIVISION
  ADD (CREATE_TIME DATE DEFAULT SYSDATE);
INSERT INTO STOCK_TIME_DIVISION (STOCK_CODE, STOCK_NAME, STOCK_DATE, NET_VALUE, VOL, NET_VALUE_2, TEMP)
VALUES (:1, :2, :3, :4, :5, :6, :7);

/**
  股票的详细信息,
  2，股票代码，股票名称，最新价，涨跌额，涨跌幅，振幅，成交量，成交额，昨收，今开，最高，最低，备注
  STOCK_TYPE+STOCK_CODE == 唯一编码
 */
CREATE TABLE STOCK_INFO (
  STOCK_TYPE       VARCHAR2(1), -- 在请求详细数据的事情，拼接股票代码来当做ID
  STOCK_CODE       VARCHAR2(255),
  STOCK_NAME       VARCHAR2(255),
  NOW_PRICE        VARCHAR2(255),
  UPS_DOWNS_PRICE  VARCHAR2(25),
  UPS_DOWNS_PCT    VARCHAR2(25),
  AMPLITUDE        VARCHAR2(255),
  VOL              VARCHAR2(255),
  TRADING_VOLUME   VARCHAR2(255),
  YESTERDAY_CLOSED VARCHAR2(255),
  THIS_OPEN        VARCHAR2(255),
  MAX_VALUE        VARCHAR2(255),
  MIN_VALUE        VARCHAR2(255),
  REMARK           VARCHAR2(1000)
);
ALTER TABLE STOCK_INFO
  ADD (CREATE_TIME DATE DEFAULT SYSDATE);
INSERT INTO STOCK_INFO (STOCK_TYPE, STOCK_CODE, STOCK_NAME, NOW_PRICE, UPS_DOWNS_PRICE, UPS_DOWNS_PCT, AMPLITUDE, VOL, TRADING_VOLUME, YESTERDAY_CLOSED, THIS_OPEN, MAX_VALUE, MIN_VALUE, REMARK)
VALUES (:1, :2, :3, :4, :5, :6, :6, :7, :8, :9, :10, :11, :12, :13, :14, );
SELECT *
FROM STOCK_TIME_DIVISION
WHERE TO_DATE(STOCK_DATE, 'yyyy-MM-dd hh24:mi') > to_date('2018-01-02', 'yyyy-MM-dd hh24:mi')
      AND STOCK_CODE = '300208';


/**
  股票的详细信息,每日信息,
  2，股票代码，股票名称，最新价，涨跌额，涨跌幅，振幅，成交量，成交额，昨收，今开，最高，最低，备注
  STOCK_TYPE+STOCK_CODE == 唯一编码
 */
CREATE TABLE STOCK_INFO_DAY (
  STOCK_TYPE       VARCHAR2(1), -- 在请求详细数据的事情，拼接股票代码来当做ID
  STOCK_CODE       VARCHAR2(255),
  STOCK_NAME       VARCHAR2(255),
  NOW_PRICE        VARCHAR2(255),
  UPS_DOWNS_PRICE  VARCHAR2(25),
  UPS_DOWNS_PCT    VARCHAR2(25),
  AMPLITUDE        VARCHAR2(255),
  VOL              VARCHAR2(255),
  TRADING_VOLUME   VARCHAR2(255),
  YESTERDAY_CLOSED VARCHAR2(255),
  THIS_OPEN        VARCHAR2(255),
  MAX_VALUE        VARCHAR2(255),
  MIN_VALUE        VARCHAR2(255),
  REMARK           VARCHAR2(1000),
  CREATE_TIME      DATE DEFAULT SYSDATE
);

SELECT STOCK_CODE || STOCK_TYPE
FROM STOCK_INFO
WHERE STOCK_CODE NOT IN (SELECT STOCK_CODE
                         FROM STOCK_TIME_DIVISION
                         WHERE TO_DATE(STOCK_DATE, 'yyyy-MM-dd hh24:mi') > to_date('2018-01-07', 'yyyy-MM-dd hh24:mi'));

SELECT STOCK_CODE || STOCK_TYPE
FROM STOCK_INFO;
SELECT *
FROM STOCK_TIME_DIVISION
WHERE TO_DATE(STOCK_DATE, 'yyyy-MM-dd hh24:mi') > to_date('2018-01-05', 'yyyy-MM-dd hh24:mi');

SELECT
  TO_DATE(STOCK_DATE, 'YYYY-MM-DD'),
  TO_NUMBER(OPEN_MARKET),
  TO_NUMBER(CLOSE_MARKET),
  TO_NUMBER(MAX_PRICE),
  TO_NUMBER(MIN_PRICE),
  TO_NUMBER(VOL),
  STOCK_CODE
FROM STOCK_NEW_VALUE_HISTORY
WHERE STOCK_CODE = '000001' AND TO_DATE(STOCK_DATE, 'YYYY-MM-DD') > TO_DATE('2017-01-01', 'YYYY-MM-DD');
